### ISSUE TITLE
Green arcs for April Fool's Day!

### ISSUE THREAD

**Issue by EnderKerman** [Cynthia7979/Minecaea#4]
block.STAINED_GLASS, 5 or 13
I did not commit anything because github seems to refuse the encoding : (
it prefers UTF-8 for unknown reasons

**Comment by Cynthia7979** [comment]
OH NO I seemed to have missed this issue :O 

Let's have a date-checking piece of code that enables green arcs every April Fool's Day, then :)

**Comment by Cynthia7979** [comment]
Completed in commit b545fa2 (should work)

Try installing Pycharm to fix the encoding problem
